### ISSUE TITLE
Game Crash When Storm Begins

### ISSUE THREAD

**Issue by frankchm** [sgmedev/Chromatic#41]
### Expected Behaviour

As soon as the game rendered a storm in my world, it crashed. Upon attempted reload, the game still crashed.

### Actual Behaviour

<details>
<summary>Crash Report</summary>

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-12-25 00:00:56
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_1959$class_1963 net.minecraft.class_1959.method_48162(net.minecraft.class_2338)'
	at knot//com.TheSuperGamer20578.chromatic.Layouts.tint(Layouts.java:127)
	at knot//com.TheSuperGamer20578.chromatic.Layouts.applyTint(Layouts.java:138)
	at knot//net.minecraft.class_310.handler$zdn000$chromatic$tick(class_310.java:4691)
	at knot//net.minecraft.class_310.method_1574(class_310.java)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.TheSuperGamer20578.chromatic.Layouts.tint(Layouts.java:127)
	at knot//com.TheSuperGamer20578.chromatic.Layouts.applyTint(Layouts.java:138)
	at knot//net.minecraft.class_310.handler$zdn000$chromatic$tick(class_310.java:4691)

-- Uptime --
Details:
	JVM uptime: 97.326s
	Wall uptime: 79.716s
	High-res time: 74.359s
	Client ticks: 365 ticks / 18.250s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['AntMess97'/170, l='ClientLevel', x=-46.77, y=85.00, z=7.03]]
	Chunk stats: 5041, 1196
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4414737 game time, 5522310 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 148

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advancementplaques, appleskin, ayame_paperdoll, bettermounthud, bettertridents, biomeinfo, bobby, capes, chat_heads, chesttracker, chiseled-bookshelf-visualizer, chromatic, cloth-config, cristellib, eatinganimationid, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, forgeconfigapiport, inventoryhud, inventoryprofilesnext, iris, iteminteractions, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, lambdynlights, libipn, modmenu, notenoughanimations, owo, physicsmod, pride, realisticbees, rrls, sereneseasons, shouldersurfing, skinlayers3d, smoothswapping, sodium, sound_physics_remastered, spruceui, trade_cycling, tslatentitystatus, visuality, waveycapes, whereisit, wildfire_gender, wthit, yet_another_config_lib_v3, zoomify, file/Stay_True_1.21.zip, minecraft:physicsmod, file/Better Trident v2.zip, file/astraliyte-s-animated-textures-v1-4.zip, file/artisans-armory-2-0.zip, file/[1.4.1] Enhanced Boss Bars.zip, file/BetterToolsWeaponsRemastered[7].zip, file/§5§lMCD Dark Katana.zip, file/Brewing Guide 1.20.1.zip, file/overgrown-flowery-gui.zip, file/Extra Flowery GUI.zip

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 866456344 bytes (826 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5612
	Graphics card #1 name: Intel(R) HD Graphics 530
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.101.2111
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 37527.54
	Virtual memory used (MiB): 20044.99
	Swap memory total (MiB): 4864.00
	Swap memory used (MiB): 283.59
	Space in storage for jna.tmpdir (MiB): available: 48070.72, total: 474780.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 48070.72, total: 474780.00
	Space in storage for io.netty.native.workdir (MiB): available: 48070.72, total: 474780.00
	Space in storage for java.io.tmpdir (MiB): available: 48070.72, total: 474780.00
	Space in storage for workdir (MiB): available: 48070.72, total: 474780.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.7
		appleskin: AppleSkin 3.0.6+mc1.21.3
			cloth-config: Cloth Config v16 16.0.141
				cloth-basic-math: cloth-basic-math 0.6.1
		areas: Areas 6.0
		ayame_paperdoll: Ayame PaperDoll 4.2.1+1.21.3
		badpackets: Bad Packets 0.8.1
		bettermounthud: Better Mount HUD 1.2.5
		bettertridents: Better Tridents 21.3.0
		biomeinfo: BiomeInfo 1.21-18
		bobby: Bobby 5.2.5+mc1.21.2
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		capes: Capes 1.5.4+1.21.2
		chat_heads: Chat Heads 0.13.5
		chesttracker: Chest Tracker 2.6.3+1.21.3
			whereisit: Where Is It 2.6.4+1.21.2
				jackfredlib: JackFredLib 0.10.3+1.21.2
					jackfredlib-base: JackFredLib: Base 1.4.1+1.21.2
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21.2
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21.2
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21.2
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21.2
					jackfredlib-toasts: JackFredLib: Toasts 1.1.1+1.21.2
		chiseled-bookshelf-visualizer: Chiseled Bookshelf Visualizer 4.0
			com_github_fracpete_romannumerals4j: romannumerals4j 0.0.1
		chromatic: Chromatic 1.2.2
			org_jglr_jchroma_jchroma_: JChroma 0.1
		collective: Collective 7.89
		cristellib: Cristel Lib 1.2.9
			blue_endless_jankson: jankson 1.2.3
		cryingportals: Crying Portals 2.8
		cyclepaintings: Cycle Paintings 3.6
		doubledoors: Double Doors 6.0
		easyshulkerboxes: Easy Shulker Boxes 21.3.0
			iteminteractions: Item Interactions 21.3.1
		eatinganimationid: Eating Animation 1.21.3+1.9.73
		entity_model_features: Entity Model Features 2.2.7
		entity_texture_features: Entity Texture Features 6.2.6
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.1
		fabric-api: Fabric API 0.107.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+d21566ae40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.79+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+6c3b5d4940
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+c47b9d4340
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.6+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+1ff58ec240
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+d9873d8b40
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.15+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.6+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.10+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+e7c9ab6640
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4340
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+4402f4ee40
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+c47b9d4340
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+89cb0a4e40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+89cb0a4e40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+c47b9d4340
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+c47b9d4340
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+c47b9d4340
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+e82f21f740
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+c47b9d4340
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+c47b9d4340
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.3
		forgeconfigapiport: Forge Config API Port 21.3.1
			com_electronwill_night-config_core: core 3.8.1
			com_electronwill_night-config_toml: toml 3.8.1
		glitchcore: GlitchCore 2.2.0.5
			net_jodah_typetools: typetools 0.6.3
		guiclock: GUI Clock 4.6
		guicompass: GUI Compass 4.8
		iceberg: Iceberg 1.2.10
		inventoryhud: Inventory HUD + 3.4.27
		inventoryprofilesnext: Inventory Profiles Next 2.0.9
		inventorytotem: Inventory Totem 3.3
		iris: Iris 1.8.0-beta.6+mc1.21.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lambdynlights: LambDynamicLights 3.2.2+1.21.3
			pride: Pride Lib 1.3.0+1.21.2
			spruceui: SpruceUI 6.1.0+1.21.2
		libipn: libIPN 6.1.1
		lithostitched: Lithostitched 1.3.5
		minecraft: Minecraft 1.21.3
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mousetweaks: Mouse Tweaks 2.27
		mr_multiple_usestew: Multiple Use Stew 1.1
		notenoughanimations: NotEnoughAnimations 1.8.1
		owo: oωo 0.12.18+1.21.2
			io_wispforest_endec: endec 0.1.9
			io_wispforest_endec_gson: gson 0.1.6
			io_wispforest_endec_jankson: jankson 0.1.6
			io_wispforest_endec_netty: netty 0.1.5
		physicsmod: Physics Mod 3.0.21
		piglinnames: Piglin Names 1.1
		puzzleslib: Puzzles Lib 21.3.14
		randomvillagenames: Random Village Names 3.7
		realisticbees: Realistic Bees 4.0
		rrls: Remove Reloading Screen 5.0.9+mc1.21.2-fabric
		sereneseasons: SereneSeasons 10.2.0.1
		shouldersurfing: Shoulder Surfing Reloaded 4.6.1
		skinlayers3d: 3d-Skin-Layers 1.7.1
		smoothswapping: Smooth Swapping 0.9.4
		sodium: Sodium 0.6.0-beta.4+mc1.21.3
		sound_physics_remastered: Sound Physics Remastered 1.21.3-1.4.6
		t_and_t: Towns and Towers 1.13.3
		terralith: Terralith 2.5.6
		trade_cycling: Trade Cycling 1.21.3-1.0.15
		tslatentitystatus: TES 1.7
		villagernames: Villager Names 8.1
		visuality: Visuality 0.7.8+1.21.3
		waveycapes: WaveyCapes 1.4.11
		wildfire_gender: Wildfire's Female Gender Mod 4.2+1.21.2
		wthit: wthit 13.1.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.2+1.21.3
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.2
	Loaded Shaderpack: ComplementaryReimagined_r5.3.zip
		Profile: Custom (+47 options changed by user)
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation
	Window size: 1680x987
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.' x 24
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 32/32 chunks
	Resource Packs: vanilla, fabric, advancementplaques, appleskin (incompatible), ayame_paperdoll, bettermounthud, bettertridents, biomeinfo, bobby, capes, chat_heads, chesttracker, chiseled-bookshelf-visualizer, chromatic, cloth-config, cristellib, eatinganimationid, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, forgeconfigapiport, inventoryhud, inventoryprofilesnext, iris, iteminteractions, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, lambdynlights, libipn, modmenu, notenoughanimations, owo, physicsmod, pride, realisticbees (incompatible), rrls, sereneseasons (incompatible), shouldersurfing, skinlayers3d, smoothswapping, sodium, sound_physics_remastered, spruceui, trade_cycling, tslatentitystatus, visuality, waveycapes, whereisit, wildfire_gender, wthit, yet_another_config_lib_v3 (incompatible), zoomify, file/Stay_True_1.21.zip (incompatible), minecraft:physicsmod (incompatible), file/Better Trident v2.zip (incompatible), file/astraliyte-s-animated-textures-v1-4.zip (incompatible), file/artisans-armory-2-0.zip (incompatible), file/[1.4.1] Enhanced Boss Bars.zip (incompatible), file/BetterToolsWeaponsRemastered[7].zip (incompatible), file/§5§lMCD Dark Katana.zip (incompatible), file/Brewing Guide 1.20.1.zip (incompatible), file/overgrown-flowery-gui.zip (incompatible), file/Extra Flowery GUI.zip (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['AntMess97'/170, l='ServerLevel[Kiki's World]', x=-46.77, y=85.00, z=7.03]]
	Active Data Packs: vanilla, fabric, bettertridents (incompatible), collective, easyshulkerboxes (incompatible), fabric-convention-tags-v2, lithostitched, mr_multiple_usestew, sereneseasons (incompatible), t_and_t, terralith, tslatentitystatus, file/ChestItemDisplay_for1-21-1_v1-2.zip (incompatible), file/Kaths-Beacon-Extended.zip (incompatible), file/never-to-expensive-v1-0-1.zip (incompatible), file/protect-farmland.zip (incompatible), winter_drop, bettertridents:boosted_impaling
	Available Data Packs: bettertridents (incompatible), bettertridents:boosted_impaling, collective, easyshulkerboxes (incompatible), fabric, fabric-convention-tags-v2, file/ChestItemDisplay_for1-21-1_v1-2.zip (incompatible), file/Kaths-Beacon-Extended.zip (incompatible), file/never-to-expensive-v1-0-1.zip (incompatible), file/protect-farmland.zip (incompatible), lithostitched, minecart_improvements, mr_multiple_usestew, redstone_experiments, sereneseasons (incompatible), t_and_t, terralith, trade_rebalance, tslatentitystatus, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla, minecraft:winter_drop
	World Generation: Experimental
	World Seed: 3770930364021930691
	Suppressed Exceptions: ~~NONE~~
```

</details>

### Steps to Reproduce

1. Load the game and see if a storm causes a crash.

### Additional Information

I have a lot of mods, so idk if it's a problem with your base file or mod incompatibility. Only mod I can think of on the surface is I am using Physics mod which adds a sandstorm effect during thunderstorms when you are in warm biomes. Not sure if that conflicts with the source code you have.

Edit: I also have Serene Seasons, which changes which biomes have rain or not.

**Comment by TheSuperGamer20578** [comment]
This appears to be an incompatibility with Minecraft 1.21.3. I've been a bit busy lately so I haven't had time to keep up with Minecraft updates. I should have some more time now though, so I'll try to get an update out within the next week or so.
